package com.dennis.telmed.navigation

const val ROUTE_HOME="home"
const val ROUTE_LOGIN="login"
const val ROUTE_REGISTER="register"
const val ROUTE_DOCTOR="doctor"
const val ROUTE_APPOINTMENT="appointment"
const val ROUTE_PAYMENT="payment"
const val ROUTE_VOICECALL="voicecall"
const val ROUTE_ADD="add"
const val ROUTE_VIEW="view"
const val ROUTE_UPDATE="update"
const val ROUTE_UPLOAD="upload"
const val ROUTE_WHATSAPP="whatsapp"
const val ROUTE_REMINDER="reminder"